// Auto-generated from public/index.html static Acquire section.
// Migrated to React so it actually renders on the live homepage (see /docs deploy notes).

export type AcquireCategory =
  | "humanoid"
  | "quadruped"
  | "drone"
  | "ebike"
  | "arm"
  | "supplier"
  | "cleaning";

export interface AcquireSpec {
  label: string;
  value: string;
}

export interface AcquireProduct {
  id: string;
  category: AcquireCategory;
  name: string;
  maker: string | null;
  makerUrl: string | null;
  description: string;
  image: string | null;
  imageAlt: string | null;
  ribbon: string | null;
  badge: string | null;
  badgeColor: "green" | "gold" | "indigo" | null;
  specs: AcquireSpec[];
  bundle: string | null;
  priceLabel: string;
  priceValue: number | null; // USD, for filtering. null = "Contact"/custom pricing
  priceSub: string | null;
  ctaText: string;
  ctaHref: string | null; // external link, or null to open the quote modal
}

export const CATEGORY_LABELS: Record<AcquireCategory, string> = {
  humanoid: "Humanoids",
  quadruped: "Quadrupeds",
  drone: "Drones",
  ebike: "eBikes & Scooters",
  arm: "Robot Arms",
  supplier: "Component Suppliers",
  cleaning: "Cleaning & Service",
};

export const ACQUIRE_PRODUCTS: AcquireProduct[] = [
  {
    id: "asimov-menlo-research-here-be-dragons-diy-kit",
    category: "humanoid",
    name: "Here Be Dragons \u2014 DIY Kit",
    maker: "Asimov / Menlo Research",
    makerUrl: "https://asimov.inc",
    description: "Build your own open-source humanoid. 1.2m, 35kg, 25 DOF, fully modular with off-the-shelf parts and 3D-printable components. The most affordable path to a working humanoid.",
    image: "/images/platforms/asimov_diy_kit.png",
    imageAlt: "Here Be Dragons humanoid kit",
    ribbon: "Presale Open",
    badge: "Preview",
    badgeColor: "gold",
    specs: [{ label: "Height", value: "1.2 m" }, { label: "DOF", value: "25+2" }, { label: "Weight", value: "35 kg" }, { label: "Source", value: "Open" }],
    bundle: "$499 deposit \u00b7 $15,000 target price \u00b7 TechMedix compatible",
    priceLabel: "$15,000",
    priceValue: 15000.0,
    priceSub: "$499 deposit secures your place",
    ctaText: "Presale at Asimov.inc",
    ctaHref: "https://asimov.inc/diy-kit",
  },
  {
    id: "rotaku-domo-developer",
    category: "humanoid",
    name: "Domo \u2014 Developer",
    maker: "Rotaku",
    makerUrl: "https://www.rotaku.ai",
    description: "Entry-level programmable humanoid for makers and educators. 23 DOF, 90 cm tall, up to 2h runtime. Includes SDK, documentation, and full-body control API.",
    image: "/images/platforms/rotaku_domo.jpg",
    imageAlt: "Rotaku Domo humanoid robot",
    ribbon: "Developer Pick",
    badge: "Preview",
    badgeColor: "gold",
    specs: [{ label: "Height", value: "90 cm" }, { label: "DOF", value: "23" }, { label: "Runtime", value: "2h" }, { label: "SDK", value: "Full access" }],
    bundle: "$99 deposit \u00b7 From $2,999 \u00b7 TechMedix compatible",
    priceLabel: "$2,999",
    priceValue: 2999.0,
    priceSub: "$99 deposit at rotaku.ai",
    ctaText: "Reserve at Rotaku",
    ctaHref: "https://www.rotaku.ai",
  },
  {
    id: "unitree-robotics-g1-basic",
    category: "humanoid",
    name: "G1 Basic",
    maker: "Unitree Robotics",
    makerUrl: "https://unitree.com",
    description: "Entry-level commercial humanoid. Ideal for research, education, and proof-of-concept deployments with full SDK access.",
    image: "/images/platforms/unitree_g1.jpg",
    imageAlt: "G1 Basic",
    ribbon: null,
    badge: "Active",
    badgeColor: "green",
    specs: [{ label: "Height", value: "127 cm" }, { label: "DOF", value: "43 joints" }, { label: "Battery", value: "2h runtime" }, { label: "SDK", value: "ROS 2" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "$17,990",
    priceValue: 17990.0,
    priceSub: "+ $499 onboarding \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "unitree-robotics-g1-edu",
    category: "humanoid",
    name: "G1 EDU",
    maker: "Unitree Robotics",
    makerUrl: "https://unitree.com",
    description: "Full research platform with dexterous hands, expanded sensors, and unrestricted developer access for AI training.",
    image: "/images/platforms/unitree_g1.jpg",
    imageAlt: "G1 EDU",
    ribbon: null,
    badge: "Active",
    badgeColor: "green",
    specs: [{ label: "Hands", value: "Dexterous" }, { label: "Sensors", value: "Full suite" }, { label: "Access", value: "Unrestricted" }, { label: "SDK", value: "ROS 2" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "$43,500",
    priceValue: 43500.0,
    priceSub: "+ $499 onboarding \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "unitree-robotics-h1-2",
    category: "humanoid",
    name: "H1-2",
    maker: "Unitree Robotics",
    makerUrl: "https://unitree.com",
    description: "Industrial-grade full-size humanoid. Upgraded actuators, enhanced stability, modular payload system for enterprise factory and logistics.",
    image: "/images/platforms/unitree_h1.jpg",
    imageAlt: "Unitree H1-2 humanoid robot",
    ribbon: "Most Requested",
    badge: "Active",
    badgeColor: "green",
    specs: [{ label: "Height", value: "1.8 m" }, { label: "Payload", value: "30 kg" }, { label: "Speed", value: "3.3 m/s" }, { label: "Runtime", value: "90 min" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "$122,455",
    priceValue: 122455.0,
    priceSub: "+ $499 onboarding \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "boston-dynamics-spot",
    category: "quadruped",
    name: "Spot",
    maker: "Boston Dynamics",
    makerUrl: "https://bostondynamics.com/products/spot",
    description: "The industrial inspection standard. Oil and gas, construction, utilities, public safety. Modular payload for sensors, cameras, robotic arm. IP54 rated.",
    image: "/images/platforms/bostondynamics_spot.jpg",
    imageAlt: "Spot",
    ribbon: "Most Requested",
    badge: "Compatible",
    badgeColor: "gold",
    specs: [{ label: "Weight", value: "32.5 kg" }, { label: "Payload", value: "14 kg" }, { label: "Battery", value: "90 min" }, { label: "IP", value: "IP54" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "Contact",
    priceValue: null,
    priceSub: "Enterprise pricing \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "dji-agriculture-agras-t50",
    category: "drone",
    name: "Agras T50",
    maker: "DJI Agriculture",
    makerUrl: "https://ag.dji.com",
    description: "Professional agricultural drone. 40 kg payload, 40L spray tank, radar + vision obstacle avoidance, AI route planning. Dominant in precision farming globally.",
    image: "/images/platforms/dji_agras_t50.jpg",
    imageAlt: "DJI Agras T50",
    ribbon: "Agricultural Leader",
    badge: "Compatible",
    badgeColor: "gold",
    specs: [{ label: "Payload", value: "40 kg" }, { label: "Tank", value: "40L spray" }, { label: "Avoidance", value: "Radar+Vision" }, { label: "Nav", value: "AI Route" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "Contact",
    priceValue: null,
    priceSub: "Enterprise pricing \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "lime-business-fleet-ebike-program",
    category: "ebike",
    name: "Fleet eBike Program",
    maker: "Lime Business",
    makerUrl: "https://li.me/business",
    description: "Enterprise eBike fleet deployment for campus, corporate, and last-mile operators. Includes IoT connectivity, swappable batteries, and fleet management dashboard.",
    image: "/images/platforms/lime_ebike.jpg",
    imageAlt: "Lime Gen 4",
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Min Fleet", value: "25 units" }, { label: "Battery", value: "Swappable" }, { label: "Diag", value: "IoT real-time" }, { label: "Support", value: "24/7" }],
    bundle: "Includes Installation + 12 mo TechMedix Fleet",
    priceLabel: "Contact",
    priceValue: null,
    priceSub: "Volume pricing \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "rad-power-bikes-radcommercial-fleet",
    category: "ebike",
    name: "RadCommercial Fleet",
    maker: "Rad Power Bikes",
    makerUrl: "https://radpowerbikes.com/commercial",
    description: "Last-mile delivery fleet program. 750W motor, 45+ mile range, 120 lb payload. Used by FedEx, DHL, and Amazon delivery contractors. Bulk fleet pricing available.",
    image: "/images/platforms/rad_power.svg",
    imageAlt: "Rad Power Commercial",
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Motor", value: "750W" }, { label: "Range", value: "45+ miles" }, { label: "Payload", value: "120 lbs" }, { label: "Min Order", value: "10 units" }],
    bundle: "Includes Installation + 12 mo TechMedix Fleet",
    priceLabel: "From $2,199",
    priceValue: 2199.0,
    priceSub: "per unit \u00b7 volume discounts available",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "robo-robotics-robo-1",
    category: "arm",
    name: "ROBO-1",
    maker: "ROBO Robotics",
    makerUrl: "https://robo.inc",
    description: "6-DOF robot arm with gripper, built for teachable, repeatable automation. Train a policy once on demonstration data, deploy to any ROBO-1 in the fleet. Native LeRobot support, MuJoCo digital twin, and Agent API for multi-arm pipeline orchestration.",
    image: "/images/platforms/robo_inc.png",
    imageAlt: "ROBO-1 robot arm",
    ribbon: "New \u2014 Arm",
    badge: null,
    badgeColor: null,
    specs: [{ label: "DOF", value: "6 + gripper" }, { label: "Reach", value: "700 mm" }, { label: "Payload", value: "1 kg" }, { label: "Weight", value: "<3 kg" }, { label: "API", value: "Agent API + LeRobot" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "$2,499",
    priceValue: 2499.0,
    priceSub: "+ $499 onboarding \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "ufactory-xarm-6",
    category: "arm",
    name: "xArm 6",
    maker: "UFACTORY",
    makerUrl: "https://www.ufactory.cc",
    description: "6-DOF collaborative robot arm with integrated controller and vision. Ideal for research, light manufacturing, and education. Supports ROS 2, MoveIt, and Python SDK.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: "Compatible",
    badgeColor: "gold",
    specs: [{ label: "DOF", value: "6" }, { label: "Reach", value: "700 mm" }, { label: "Payload", value: "5 kg" }, { label: "SDK", value: "ROS 2" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "$5,500",
    priceValue: 5500.0,
    priceSub: "+ $499 onboarding \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "kinova-robotics-gen3",
    category: "arm",
    name: "Gen3",
    maker: "Kinova Robotics",
    makerUrl: "https://www.kinovarobotics.com",
    description: "7-DOF lightweight robotic arm for research. Carbon fiber construction, torque sensors in every joint, ROS 2 native. Field-proven in 60+ research labs worldwide.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: "Preview",
    badgeColor: "indigo",
    specs: [{ label: "DOF", value: "7" }, { label: "Reach", value: "900 mm" }, { label: "Payload", value: "4 kg" }, { label: "Weight", value: "7.2 kg" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "$12,000",
    priceValue: 12000.0,
    priceSub: "+ $499 onboarding \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "universal-robots-ur5e",
    category: "arm",
    name: "UR5e",
    maker: "Universal Robots",
    makerUrl: "https://www.universal-robots.com",
    description: "Collaborative robot arm with built-in force sensing and intuitive teach pendant. 50,000+ installations across manufacturing, labs, and logistics worldwide.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: "Compatible",
    badgeColor: "gold",
    specs: [{ label: "DOF", value: "6" }, { label: "Reach", value: "850 mm" }, { label: "Payload", value: "5 kg" }, { label: "Weight", value: "20.6 kg" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "$22,000",
    priceValue: 22000.0,
    priceSub: "+ $499 onboarding \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "asia-japan-harmonic-drive-systems",
    category: "supplier",
    name: "Harmonic Drive Systems",
    maker: "Asia \u00b7 Japan",
    makerUrl: null,
    description: "Precision strain wave gear reducers. 20\u201325% global market share in humanoid reducers. Critical path supplier \u2014 limited alternative sources.",
    image: null,
    imageAlt: null,
    ribbon: "Bottleneck",
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Reducer" }, { label: "Share", value: "20\u201325%" }, { label: "Ticker", value: "6324.T" }, { label: "Unit", value: "$1,800" }],
    bundle: null,
    priceLabel: "$1,800",
    priceValue: 1800.0,
    priceSub: "per reducer unit",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/harmonic_drive",
  },
  {
    id: "asia-china-leaderdrive",
    category: "supplier",
    name: "Leaderdrive",
    maker: "Asia \u00b7 China",
    makerUrl: null,
    description: "Cycloidal gearbox and reducer manufacturer. Key Unitree H1 supplier for joint actuator reduction stages. Concentrated supply risk in China.",
    image: null,
    imageAlt: null,
    ribbon: "Bottleneck",
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Reducer" }, { label: "Region", value: "CN" }, { label: "Risk", value: "High" }, { label: "Unit", value: "$1,800" }],
    bundle: null,
    priceLabel: "$1,800",
    priceValue: 1800.0,
    priceSub: "per reducer unit",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/leaderdrive",
  },
  {
    id: "asia-china-nanjing-kgm",
    category: "supplier",
    name: "Nanjing KGM",
    maker: "Asia \u00b7 China",
    makerUrl: null,
    description: "Brushless DC motor and integrated actuator assemblies. Supplies H1 joint drive units. High concentration risk as sole-source for several H1 motor configurations.",
    image: null,
    imageAlt: null,
    ribbon: "Bottleneck",
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Actuator" }, { label: "Region", value: "CN" }, { label: "Risk", value: "High" }, { label: "Unit", value: "$950" }],
    bundle: null,
    priceLabel: "$950",
    priceValue: 950.0,
    priceSub: "per actuator unit",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/nanjing_kgm",
  },
  {
    id: "north-america-us-nvidia",
    category: "supplier",
    name: "NVIDIA",
    maker: "North America \u00b7 US",
    makerUrl: null,
    description: "Jetson and Isaac robotics edge AI platforms. ~70\u201380% share in robotics edge AI compute. Powers H1 perception and motion planning stack.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "PCB / AI" }, { label: "Share", value: "~75%" }, { label: "Ticker", value: "NVDA" }, { label: "Unit", value: "$499" }],
    bundle: null,
    priceLabel: "$499",
    priceValue: 499.0,
    priceSub: "per compute module",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/nvidia",
  },
  {
    id: "asia-china-cubemars",
    category: "supplier",
    name: "CubeMars",
    maker: "Asia \u00b7 China",
    makerUrl: null,
    description: "Compact frameless torque motors and integrated actuator modules. Supplies H1 shoulder and elbow joint actuators. Known for high torque density.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Actuator" }, { label: "Region", value: "CN" }, { label: "Risk", value: "Low" }, { label: "Unit", value: "$420" }],
    bundle: null,
    priceLabel: "$420",
    priceValue: 420.0,
    priceSub: "per actuator unit",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/cubemars",
  },
  {
    id: "asia-china-hesai-technology",
    category: "supplier",
    name: "Hesai Technology",
    maker: "Asia \u00b7 China",
    makerUrl: null,
    description: "LiDAR and depth sensing for humanoid navigation. 33% share of automotive LiDAR. Supplies H1 environmental perception sensors.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Sensor" }, { label: "Share", value: "33%" }, { label: "Ticker", value: "HSAI" }, { label: "Unit", value: "$380" }],
    bundle: null,
    priceLabel: "$380",
    priceValue: 380.0,
    priceSub: "per sensor unit",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/hesai",
  },
  {
    id: "asia-china-catl",
    category: "supplier",
    name: "CATL",
    maker: "Asia \u00b7 China",
    makerUrl: null,
    description: "World's largest battery cell manufacturer. ~37% EV battery market share. Supplies H1 main power pack cells. Dominant in large-format lithium cells.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Battery" }, { label: "Share", value: "~37%" }, { label: "Ticker", value: "300750.SZ" }, { label: "Unit", value: "$1,200" }],
    bundle: null,
    priceLabel: "$1,200",
    priceValue: 1200.0,
    priceSub: "per battery pack",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/catl",
  },
  {
    id: "asia-japan-sony-semiconductor",
    category: "supplier",
    name: "Sony Semiconductor",
    maker: "Asia \u00b7 Japan",
    makerUrl: null,
    description: "CMOS image sensors for vision systems. ~44% global CMOS share. Supplies H1 camera arrays for stereo vision and SLAM.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Sensor" }, { label: "Share", value: "~44%" }, { label: "Ticker", value: "SONY" }, { label: "Unit", value: "$380" }],
    bundle: null,
    priceLabel: "$380",
    priceValue: 380.0,
    priceSub: "per sensor module",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/sony_sensors",
  },
  {
    id: "europe-germany-bosch-sensortec",
    category: "supplier",
    name: "Bosch Sensortec",
    maker: "Europe \u00b7 Germany",
    makerUrl: null,
    description: "MEMS IMU and inertial sensors for balance and motion estimation. ~23\u201327% MEMS IMU market share. Critical for H1 bipedal stability control.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Sensor" }, { label: "Share", value: "~25%" }, { label: "Region", value: "DE" }, { label: "Unit", value: "$380" }],
    bundle: null,
    priceLabel: "$380",
    priceValue: 380.0,
    priceSub: "per IMU module",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/bosch_sensortec",
  },
  {
    id: "asia-china-sharpa-robotics",
    category: "supplier",
    name: "Sharpa Robotics",
    maker: "Asia \u00b7 China",
    makerUrl: null,
    description: "Dexterous robotic hand assemblies with integrated tactile sensing. Supplies H1 end-effector hand modules for manipulation tasks.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Hand" }, { label: "Region", value: "CN" }, { label: "DOF", value: "Multi" }, { label: "Unit", value: "$2,400" }],
    bundle: null,
    priceLabel: "$2,400",
    priceValue: 2400.0,
    priceSub: "per hand assembly",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/sharpa",
  },
  {
    id: "europe-germany-skf",
    category: "supplier",
    name: "SKF",
    maker: "Europe \u00b7 Germany",
    makerUrl: null,
    description: "Precision bearings for joint rotation and load bearing. ~20% industrial bearing market share. Supplies H1 ankle, knee, and hip bearing assemblies.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Bearing" }, { label: "Share", value: "~20%" }, { label: "Ticker", value: "SKF-B.ST" }, { label: "Unit", value: "$95" }],
    bundle: null,
    priceLabel: "$95",
    priceValue: 95.0,
    priceSub: "per bearing set",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/skf",
  },
  {
    id: "asia-taiwan-tsmc",
    category: "supplier",
    name: "TSMC",
    maker: "Asia \u00b7 Taiwan",
    makerUrl: null,
    description: "Advanced node semiconductor fabrication. ~90% share of sub-5nm chips. Manufactures custom AI inference ASICs used in H1 edge compute modules.",
    image: null,
    imageAlt: null,
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Type", value: "Fab" }, { label: "Share", value: "~90%" }, { label: "Ticker", value: "TSM" }, { label: "Unit", value: "$380" }],
    bundle: null,
    priceLabel: "$380",
    priceValue: 380.0,
    priceSub: "per compute die equiv.",
    ctaText: "Atlas Profile",
    ctaHref: "https://humanoids.fyi/companies/tsmc",
  },
  {
    id: "avidbots-neo-2",
    category: "cleaning",
    name: "Neo 2",
    maker: "Avidbots",
    makerUrl: "https://avidbots.com",
    description: "Commercial floor scrubbing AMR with fully autonomous path planning and cloud-based fleet management. Deployed at airports, warehouses, and retail at scale.",
    image: "/images/platforms/avidbots_neo2.svg",
    imageAlt: "Avidbots Neo 2 floor scrubbing AMR",
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Coverage", value: "3,500 m\u00b2/hr" }, { label: "Runtime", value: "4.5 hrs" }, { label: "Connect", value: "WiFi / 4G" }, { label: "Type", value: "Floor Scrubber" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "Contact",
    priceValue: null,
    priceSub: "Enterprise pricing \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "gaussian-robotics-phantas",
    category: "cleaning",
    name: "Phantas",
    maker: "Gaussian Robotics",
    makerUrl: "https://gaussian-robotics.com",
    description: "Multi-function autonomous scrubber and sweeper for retail and logistics. AI map learning, multi-machine coordination, and cloud fleet oversight.",
    image: "/images/platforms/gaussian_phantas.jpg",
    imageAlt: "Gaussian Robotics Phantas autonomous scrubber",
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Coverage", value: "3,200 m\u00b2/hr" }, { label: "Runtime", value: "4 hrs" }, { label: "Connect", value: "WiFi" }, { label: "Use", value: "Retail / 3PL" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "Contact",
    priceValue: null,
    priceSub: "Enterprise pricing \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "k-rcher-kira-b-50",
    category: "cleaning",
    name: "KIRA B 50",
    maker: "K\u00e4rcher",
    makerUrl: "https://karcher.com",
    description: "Professional B2B autonomous floor cleaning robot with laser-SLAM navigation, IoT telemetry, and intelligent water management for large commercial indoor spaces.",
    image: "/images/platforms/karcher_kira_b50.jpg",
    imageAlt: "Karcher KIRA B 50",
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Coverage", value: "1,500 m\u00b2/hr" }, { label: "Runtime", value: "3 hrs" }, { label: "Connect", value: "WiFi" }, { label: "Type", value: "Scrubber AMR" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "Contact",
    priceValue: null,
    priceSub: "Enterprise pricing \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "diversey-johnsoncontrols-intellibot-swingobot",
    category: "cleaning",
    name: "Intellibot Swingobot",
    maker: "Diversey / JohnsonControls",
    makerUrl: "https://diversey.com",
    description: "Enterprise cleaning AMR from the Diversey Taski line, deployed by JohnsonControls FM teams. Autonomous scrubbing and sweeping with remote monitoring for large commercial campuses.",
    image: "/images/platforms/taski_swingobot.jpg",
    imageAlt: "Taski Intellibot Swingobot",
    ribbon: null,
    badge: null,
    badgeColor: null,
    specs: [{ label: "Coverage", value: "2,000 m\u00b2/hr" }, { label: "Runtime", value: "3.5 hrs" }, { label: "Connect", value: "WiFi / 4G" }, { label: "Operator", value: "JCI / FM" }],
    bundle: "Includes Platform Onboarding + 12 mo TechMedix Fleet",
    priceLabel: "Contact",
    priceValue: null,
    priceSub: "Enterprise pricing \u00b7 TechMedix free yr 1",
    ctaText: "Request Quote",
    ctaHref: null,
  },

  // --- New for 2026: UBTECH UWORLD U1 series (launched June 30, 2026) ---
  // Home/companion-focused humanoids — first entries broadening our home-service coverage.
  // No local product photography yet; falls back to a placeholder icon in the UI.
  {
    id: "ubtech-uworld-u1-lite",
    category: "humanoid",
    name: "UWORLD U1 Lite",
    maker: "UBTECH Robotics",
    makerUrl: "https://www.ubtrobot.com",
    description: "Semi-torso entry point to UBTECH's UWORLD consumer line. Silicone-skin companion robot with an emotion-aware LLM, local encrypted memory, and 88 DOF. Currently shipping in China only.",
    image: null,
    imageAlt: null,
    ribbon: "New — 2026",
    badge: "Preview",
    badgeColor: "indigo",
    specs: [
      { label: "Form", value: "Semi-torso" },
      { label: "DOF", value: "88" },
      { label: "Battery", value: "2-4 hrs" },
      { label: "Memory", value: "Local encrypted" },
    ],
    bundle: "China availability only (JD.com) · TechMedix compatibility pending",
    priceLabel: "$16,500",
    priceValue: 16500,
    priceSub: "119,800 RMB · deposit reservation via JD.com",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "ubtech-uworld-u1-pro",
    category: "humanoid",
    name: "UWORLD U1 Pro",
    maker: "UBTECH Robotics",
    makerUrl: "https://www.ubtrobot.com",
    description: "Full-body companion humanoid with a dual-pivot biomimetic cervical spine for lifelike neck and head motion. Designed for companionship, elder care, reception, and hospitality use.",
    image: null,
    imageAlt: null,
    ribbon: "New — 2026",
    badge: "Preview",
    badgeColor: "indigo",
    specs: [
      { label: "Height", value: "168-183 cm" },
      { label: "Weight", value: "35-42 kg" },
      { label: "DOF", value: "88" },
      { label: "Battery", value: "2-4 hrs" },
    ],
    bundle: "China availability only (JD.com) · TechMedix compatibility pending",
    priceLabel: "$23,400",
    priceValue: 23400,
    priceSub: "169,800 RMB · full-body companion tier",
    ctaText: "Request Quote",
    ctaHref: null,
  },
  {
    id: "ubtech-uworld-u1-ultra",
    category: "humanoid",
    name: "UWORLD U1 Ultra",
    maker: "UBTECH Robotics",
    makerUrl: "https://www.ubtrobot.com",
    description: "Flagship full-body tier with UBTECH's most advanced bionic skin, gait, and expression fidelity. Male and female body variants. Closed ecosystem — no third-party developer access.",
    image: null,
    imageAlt: null,
    ribbon: "Flagship",
    badge: "Preview",
    badgeColor: "gold",
    specs: [
      { label: "Height", value: "168 or 183 cm" },
      { label: "DOF", value: "88" },
      { label: "Skin", value: "Bionic silicone" },
      { label: "Dev access", value: "Closed" },
    ],
    bundle: "China availability only (JD.com) · TechMedix compatibility pending",
    priceLabel: "From $121,400",
    priceValue: 121400,
    priceSub: "880,000-990,000 RMB by body variant",
    ctaText: "Request Quote",
    ctaHref: null,
  },
];
