#!/usr/bin/env ts-node
/**
 * scripts/atlas-to-seed.ts
 *
 * Reads all .atlas/*.json files and writes supabase/seed_atlas_generated.sql
 *
 * Usage:
 *   npx ts-node scripts/atlas-to-seed.ts
 *   # or after ts-node install:
 *   ts-node scripts/atlas-to-seed.ts
 */

import fs from "fs";
import path from "path";

const ATLAS_DIR = path.join(process.cwd(), ".atlas");
const OUT_FILE = path.join(process.cwd(), "supabase", "seed_atlas_generated.sql");

interface Company {
  id: string;
  name: string;
  type: string;
  country: string;
  description?: string;
  robotImage?: string;
  robotSpecs?: Record<string, unknown>;
}

interface SupplyChainNode {
  id: string;
  name: string;
  type: string;
  country: string;
  depth: number;
  direction: string;
  ticker?: string;
  marketShare?: string;
  isBottleneckSupplier: boolean;
}

interface Relationship {
  id: string;
  from: { id: string; name: string; type: string; country: string };
  to: { id: string; name: string; type: string; country: string };
  component: string;
  componentCategoryId: string;
  description?: string;
}

interface SupplyChainGraph {
  root: string;
  nodes: SupplyChainNode[];
}

interface CompanyProfile {
  company: Company;
  suppliers: Relationship[];
}

interface AtlasComponent {
  id: string;
  name: string;
  description: string;
  avgCostPercent?: number;
  bottleneck: boolean;
  bottleneckReason?: string;
  keyMetrics?: Record<string, string>;
}

// ── Load files ───────────────────────────────────────────────────────────────

function load<T>(filename: string): T | null {
  const fp = path.join(ATLAS_DIR, filename);
  if (!fs.existsSync(fp)) {
    console.warn(`[warn] Missing: ${filename}`);
    return null;
  }
  return JSON.parse(fs.readFileSync(fp, "utf8")) as T;
}

function esc(v: string | undefined | null): string {
  if (v == null) return "NULL";
  return `'${v.replace(/'/g, "''")}'`;
}

function escNum(v: number | undefined | null): string {
  if (v == null) return "NULL";
  return String(v);
}

function escJson(v: unknown): string {
  if (v == null) return "NULL";
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
}

// ── Component type mapping ────────────────────────────────────────────────────

const CATEGORY_TO_TYPE: Record<string, string> = {
  motors: "motor",
  reducers: "reducer",
  screws: "actuator",
  batteries: "battery",
  sensors_general: "sensor",
  pcbs: "pcb",
  compute: "pcb",
  bearings: "bearing",
  end_effectors: "hand",
  actuators_rotary: "actuator",
  skeleton: "actuator",
};

const CATEGORY_CRITICALITY: Record<string, string> = {
  motors: "high",
  reducers: "high",
  screws: "high",
  batteries: "high",
  sensors_general: "medium",
  pcbs: "medium",
  compute: "high",
  bearings: "medium",
  end_effectors: "medium",
  actuators_rotary: "high",
};

// ── Region mapping ────────────────────────────────────────────────────────────

const COUNTRY_TO_REGION: Record<string, string> = {
  CN: "Asia",
  JP: "Asia",
  KR: "Asia",
  TW: "Asia",
  US: "North America",
  DE: "Europe",
  UK: "Europe",
  FR: "Europe",
};

// ── Price estimates (USD) by category ────────────────────────────────────────

const CATEGORY_PRICE: Record<string, number> = {
  motors: 420,
  reducers: 1800,
  screws: 950,
  batteries: 1200,
  sensors_general: 380,
  pcbs: 85,
  compute: 499,
  bearings: 95,
  end_effectors: 2400,
  actuators_rotary: 420,
};

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  const companies = load<Company[]>("companies.json");
  const components = load<AtlasComponent[]>("components.json");
  const relationships = load<Relationship[]>("relationships.json");
  const supplyChain = load<SupplyChainGraph>("unitree_supply_chain.json");
  const unitreeProfile = load<CompanyProfile>("unitree_profile.json");

  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/atlas-to-seed.ts",
    "-- DO NOT edit manually — re-run the script to regenerate",
    "-- Source: .atlas/*.json (from Atlas CLI)",
    "",
    "-- ── SUPPLIERS (from Unitree supply chain) ──────────────────────",
    "",
  ];

  // ── Suppliers from supply chain nodes ────────────────────────────────────

  const nodes = supplyChain?.nodes ?? [];
  const supplierRelationships = unitreeProfile?.suppliers ?? [];

  // Map node id → category
  const nodeCategory: Record<string, string> = {};
  for (const rel of supplierRelationships) {
    nodeCategory[rel.from.id] = rel.componentCategoryId;
  }

  let supplierIdx = 1;
  const insertedSuppliers = new Set<string>();

  for (const node of nodes) {
    if (node.direction === "root" || insertedSuppliers.has(node.id)) continue;
    insertedSuppliers.add(node.id);

    const category = nodeCategory[node.id] ?? "sensors_general";
    const compType = CATEGORY_TO_TYPE[category] ?? "sensor";
    const region = COUNTRY_TO_REGION[node.country] ?? "Asia";
    const price = CATEGORY_PRICE[category];
    const seg = String(supplierIdx).padStart(12, "0");
    const uuid = `s0000000-0000-0000-${seg.slice(0,4)}-${seg.slice(4).padEnd(12, "0")}`;

    lines.push(
      `INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)`
    );
    lines.push(
      `VALUES ('${uuid}', ` +
      `${esc(node.name)}, ${esc(compType)}, ${esc(region)}, ${esc(node.country)}, ` +
      `${esc(node.id)}, ${esc(node.marketShare)}, ${esc(node.ticker)}, ` +
      `${node.isBottleneckSupplier}, ${escNum(price)})`
    );
    lines.push(`ON CONFLICT (atlas_supplier_id) DO NOTHING;`);
    lines.push("");
    supplierIdx++;
  }

  // ── Robot from Unitree profile ────────────────────────────────────────────

  lines.push("-- ── ROBOT PROFILE ──────────────────────────────────────────");
  lines.push("");

  if (unitreeProfile?.company) {
    const c = unitreeProfile.company;
    const specs = c.robotSpecs ?? {};

    lines.push(`INSERT INTO robots (id, name, platform, serial_number, location, region,`);
    lines.push(`  battery_level, health_score, status, telemetry_summary, platforms_supported, last_seen_at, last_updated)`);
    lines.push(`VALUES (`);
    lines.push(`  'r0000000-0000-0000-aaaa-000000000001',`);
    lines.push(`  'H1-DEMO-01', 'Unitree H1', 'UNI-H1-ATLAS-001', 'BlackCat Lab', 'West',`);
    lines.push(`  88, 94, 'online', '{}', ARRAY['Unitree H1'], now(), now()`);
    lines.push(`) ON CONFLICT (id) DO NOTHING;`);
    lines.push("");
    lines.push(`INSERT INTO robot_profiles (id, robot_id, model, oem, description, image_url, specs, atlas_company_id)`);
    lines.push(`VALUES (`);
    lines.push(`  'rp000000-0000-0000-aaaa-000000000001',`);
    lines.push(`  'r0000000-0000-0000-aaaa-000000000001',`);
    lines.push(`  ${esc("Unitree H1")},`);
    lines.push(`  ${esc("Unitree Robotics")},`);
    lines.push(`  ${esc(c.description)},`);
    lines.push(`  ${esc(c.robotImage)},`);
    lines.push(`  ${escJson(specs)},`);
    lines.push(`  ${esc(c.id)}`);
    lines.push(`) ON CONFLICT (id) DO NOTHING;`);
    lines.push("");
  }

  // ── Components from Atlas component categories ────────────────────────────

  lines.push("-- ── COMPONENT CATEGORIES (from Atlas) ──────────────────────");
  lines.push("");

  const atlasComps = components ?? [];
  const usedCategories = new Set(supplierRelationships.map((r) => r.componentCategoryId));

  let compIdx = 1;
  for (const cat of usedCategories) {
    const atlasComp = atlasComps.find((c) => c.id === cat);
    const rel = supplierRelationships.find((r) => r.componentCategoryId === cat);
    const compType = CATEGORY_TO_TYPE[cat] ?? "sensor";
    const criticality = CATEGORY_CRITICALITY[cat] ?? "medium";
    const cseg = String(compIdx).padStart(12, "0");
    const cuuid = `c0000000-0000-0000-${cseg.slice(0,4)}-${cseg.slice(4).padEnd(12,"0")}`;
    const name = atlasComp?.name ?? (rel?.component ?? cat);
    const desc = atlasComp?.description ?? rel?.description ?? "ATLAS_MISSING";

    lines.push(`INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)`);
    lines.push(`VALUES (`);
    lines.push(`  '${cuuid}',`);
    lines.push(`  'r0000000-0000-0000-aaaa-000000000001',`);
    lines.push(`  ${esc(name)}, ${esc(compType)}, ${esc(criticality)}, ${esc(cat)}, ${esc(desc)}`);
    lines.push(`) ON CONFLICT (id) DO NOTHING;`);
    lines.push("");
    compIdx++;
  }

  // ── Write output ──────────────────────────────────────────────────────────

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf8");

  console.log(`Generated: ${OUT_FILE}`);
  console.log(`   ${supplierIdx - 1} suppliers, ${compIdx - 1} component categories`);
  console.log("");
  console.log("To apply: paste into Supabase SQL editor after 002_blackcat_os.sql");
}

main();
