-- AUTO-GENERATED by scripts/atlas-to-seed.ts
-- DO NOT edit manually — re-run the script to regenerate
-- Source: .atlas/*.json (from Atlas CLI)

-- ── SUPPLIERS (from Unitree supply chain) ──────────────────────

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000010000', 'CubeMars', 'actuator', 'Asia', 'CN', 'cubemars', NULL, NULL, false, 420)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000020000', 'Harmonic Drive Systems', 'reducer', 'Asia', 'JP', 'harmonic_drive', '20-25%', '6324.T', true, 1800)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000030000', 'NVIDIA', 'pcb', 'North America', 'US', 'nvidia', '~70-80% (robotics edge AI)', 'NVDA', false, 499)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000040000', 'Hesai Technology', 'sensor', 'Asia', 'CN', 'hesai', '33% (auto LiDAR)', 'HSAI', false, 380)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000050000', 'Samsung Electro-Mechanics', 'pcb', 'Asia', 'KR', 'samsung_electro', NULL, NULL, false, 85)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000060000', 'SKF', 'bearing', 'Europe', 'DE', 'skf', '~20% (industrial bearings)', 'SKF-B.ST', false, 95)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000070000', 'CATL', 'battery', 'Asia', 'CN', 'catl', '~37% (EV batteries)', '300750.SZ', false, 1200)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000080000', 'Sharpa Robotics', 'hand', 'Asia', 'CN', 'sharpa', NULL, NULL, false, 2400)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000090000', 'Orbbec', 'sensor', 'Asia', 'CN', 'orbbec', NULL, NULL, false, 380)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000100000', 'Bosch Sensortec', 'sensor', 'Europe', 'DE', 'bosch_sensortec', '~23-27% (MEMS IMU)', NULL, false, 380)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000110000', 'Leaderdrive', 'reducer', 'Asia', 'CN', 'leaderdrive', NULL, NULL, true, 1800)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000120000', 'Nanjing KGM', 'actuator', 'Asia', 'CN', 'nanjing_kgm', NULL, NULL, true, 950)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000130000', 'NSK', 'bearing', 'Asia', 'JP', 'nsk', NULL, '6471.T', false, 95)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000140000', 'Sony Semiconductor', 'sensor', 'Asia', 'JP', 'sony_sensors', '~44% (CMOS image sensors)', 'SONY', false, 380)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000150000', 'JL Mag Rare-Earth', 'sensor', 'Asia', 'CN', 'jl_mag', NULL, NULL, false, 380)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

INSERT INTO suppliers (id, name, component_type, region, country, atlas_supplier_id, market_share, ticker, is_bottleneck, unit_price)
VALUES ('s0000000-0000-0000-0000-000000160000', 'TSMC', 'sensor', 'Asia', 'TW', 'tsmc', '~90% (advanced node fab)', 'TSM', false, 380)
ON CONFLICT (atlas_supplier_id) DO NOTHING;

-- ── ROBOT PROFILE ──────────────────────────────────────────

INSERT INTO robots (id, name, platform, serial_number, location, region,
  battery_level, health_score, status, telemetry_summary, platforms_supported, last_seen_at, last_updated)
VALUES (
  'r0000000-0000-0000-aaaa-000000000001',
  'H1-DEMO-01', 'Unitree H1', 'UNI-H1-ATLAS-001', 'BlackCat Lab', 'West',
  88, 94, 'online', '{}', ARRAY['Unitree H1'], now(), now()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO robot_profiles (id, robot_id, model, oem, description, image_url, specs, atlas_company_id)
VALUES (
  'rp000000-0000-0000-aaaa-000000000001',
  'r0000000-0000-0000-aaaa-000000000001',
  'Unitree H1',
  'Unitree Robotics',
  'The volume leader with 5,500+ units shipped in 2025 - more than Tesla, Figure, and Agility combined, driving ~$248M in revenue at a ~16.8% net margin. Unitree''s secret is radical cost compression: BOM of just $11.5K achieved through China''s EV and drone supply chains. Their PMSM motors (rather than the BLDC consensus) offer better response and heat dissipation. At 130 cm tall and 35 kg, G1 is significantly smaller than competitors - closer to a research platform than a human-scale worker. Filed for a STAR Market IPO in Mar 2026 targeting ~$610M, with proceeds earmarked for AI-driven intelligent robot models - signaling a strategic pivot from pure hardware to AI capabilities.',
  '/models/robo9_unitree.webp',
  '{"status":"In Production","launchDate":"Aug 2024","shipments2025":5500,"shipmentShare":"41%","targetUse":["Research","Commercial"],"mass":"35 kg","height":"130 cm","speed":"2 m/s","totalDOF":"23-43","operatingTime":"2 hrs","payloadCapacity":"6.6 lbs","endEffector":"3-finger force control (optional 5-finger)","tactileSensing":null,"locomotion":"Leg","materials":"Aluminum alloy, high-strength engineering plastic","motor":"Low inertia high-speed PMSM","actuatorBody":"Rotary","actuatorHand":"Not disclosed","transmission":"Harmonic Reducer + Planetary Reducer","externalSensors":"3D LiDAR, depth cameras 360°, GPS, IMUs","internalSensors":"3D Cameras, LiDAR, Magnetic encoders, Current loop","compute":"8-core CPU, NVIDIA Jetson Orin","battery":"2 kWh","charging":"Quick-swap / autonomous charging","aiPartner":"Not disclosed","software":"Unitree app store","dataCollection":"Not disclosed","bom":"$11.5K","price":"$13.5K"}'::jsonb,
  'unitree'
) ON CONFLICT (id) DO NOTHING;

-- ── COMPONENT CATEGORIES (from Atlas) ──────────────────────

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000010000',
  'r0000000-0000-0000-aaaa-000000000001',
  'Motors (BLDC)', 'motor', 'high', 'motors', 'Frameless brushless DC motors are the dominant choice across both US and Chinese humanoids. They provide high torque density in compact form factors.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000020000',
  'r0000000-0000-0000-aaaa-000000000001',
  'Reducers (Harmonic Drive)', 'reducer', 'high', 'reducers', 'Strain wave / harmonic reducers provide high gear ratios in compact packages with near-zero backlash. Largest single cost driver in rotary actuators.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000030000',
  'r0000000-0000-0000-aaaa-000000000001',
  'Compute', 'pcb', 'high', 'compute', 'Largely standardized on NVIDIA Jetson platform (Orin, AGX Thor). Tesla is the exception with proprietary FSD SoC. Key metrics: TOPS, TOPS/watt.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000040000',
  'r0000000-0000-0000-aaaa-000000000001',
  'General Sensors', 'sensor', 'medium', 'sensors_general', 'Cameras for perception, IMUs for orientation, force/torque sensors on joints, LiDAR for mapping. Most OEMs use 2-7 cameras.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000050000',
  'r0000000-0000-0000-aaaa-000000000001',
  'PCBs', 'pcb', 'medium', 'pcbs', 'Printed circuit boards for power distribution, sensor integration, and compute interconnects.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000060000',
  'r0000000-0000-0000-aaaa-000000000001',
  'Actuators', 'actuator', 'high', 'actuators_rotary', 'A typical humanoid uses 25-30 actuators split between two types. Rotary actuators handle joints (shoulders, elbows, hips, knees) and combine a BLDC motor + harmonic reducer + encoder + torque sensor into a single module. Linear actuators convert rotary motion to push/pull force via planetary roller screws - used in legs and torso for high-force movements. Tesla Optimus uses 20 rotary and 14 linear actuators. The actuator is where all the key components converge, making it the most cost-sensitive subsystem.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000070000',
  'r0000000-0000-0000-aaaa-000000000001',
  'Bearings', 'bearing', 'medium', 'bearings', 'Cross-roller bearings dominate hip and waist joints for their load capacity in compact form. Angular contact bearings used in secondary joints.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000080000',
  'r0000000-0000-0000-aaaa-000000000001',
  'Batteries', 'battery', 'high', 'batteries', 'Lithium-ion and lithium-polymer packs, leveraging massive cost reduction from EV industry. Operating times range 2-14 hrs. XPeng pushing solid-state.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000090000',
  'r0000000-0000-0000-aaaa-000000000001',
  'End Effectors (Hands)', 'hand', 'medium', 'end_effectors', 'Dexterous hands range from 3-finger grippers to 22-DOF anthropomorphic hands. Tendon-driven (1X, Tesla) vs motor+gear (Figure, Dexmate).'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO components (id, robot_id, name, type, criticality, atlas_component_id, description)
VALUES (
  'c0000000-0000-0000-0000-000000100000',
  'r0000000-0000-0000-aaaa-000000000001',
  'Planetary Roller Screws', 'actuator', 'high', 'screws', 'Critical bottleneck in humanoid supply chains. Convert rotary motion to linear motion with high force density. Tesla Optimus uses 1:14 planetary roller screws.'
) ON CONFLICT (id) DO NOTHING;
